          token: ${{ secrets.METRICS_TOKEN }}
          user: brolezebroleze
          template: classic
          base: "" # Isso remove o cabeçalho e as estatísticas extras
          config_timezone: America/Sao_Paulo
          
          # Configuração do Plugin People para ficar igual à foto
          plugin_people: yes
          plugin_people_types: followers, following # Mostra quem segue e quem você segue
          plugin_people_limit: 28                    # Limite de pessoas na tela
          plugin_people_size: 28                     # Tamanho dos avatares
          plugin_people_identicons: no              # Usa a foto real da pessoa
